---
- name: restart-swift-container-services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-','') }}swift-container"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-','') }}swift-container-auditor"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-','') }}swift-container-replicator"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-','') }}swift-container-sync"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-','') }}swift-container-updater"
  when: start_container|bool
