---
- name: restart swift-account-services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-', '') }}swift-account"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-', '') }}swift-account-auditor"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-', '') }}swift-account-reaper"
    - "{{ (ansible_os_family == 'RedHat') | ternary('openstack-', '') }}swift-account-replicator"
  when: start_account|bool
